
var countries = [{
    country:"Albania Lek",
    coin:"Lek",
    country_handle:"Albania",
    country_name:"Albania",
    iso2:"AL",
    iso3:"ALB",
    number:"008",
    currency_code:"ALL",
    graphic:"",
    fonta:"Lek",
    font:"&#76;&#101;&#107;",
    ariala:"Lek",
    arial:"&#76;&#101;&#107;",
    decimal:"76, 101, 107",
    hex:"4c, 65, 6b",
    comment:""
},{
    country:"Afghanistan Afghani",
    coin:"Afghani",
    country_handle:"Afghanistan",
    country_name:"Afghanistan",
    iso2:"AF",
    iso3:"AFG",
    number:"004",
    currency_code:"AFN",
    graphic:"",
    fonta:"?",
    font:"&#1547;",
    ariala:"?",
    arial:"&#1547;",
    decimal:"1547",
    hex:"60b",
    comment:""
},{
    country:"Argentina Peso",
    coin:"Peso",
    country_handle:"Argentina",
    country_name:"Argentina",
    iso2:"AR",
    iso3:"ARG",
    number:"032",
    currency_code:"ARS",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:"info"
},{
    country:"Aruba Guilder",
    coin:"Guilder",
    country_handle:"Aruba",
    country_name:"Aruba",
    iso2:"AW",
    iso3:"ABW",
    number:"533",
    currency_code:"AWG",
    graphic:"",
    fonta:"ƒ",
    font:"&#402;",
    ariala:"ƒ",
    arial:"&#402;",
    decimal:"402",
    hex:"192",
    comment:""
},{
    country:"Australia Dollar",
    coin:"Dollar",
    country_handle:"Australia",
    country_name:"Australia",
    iso2:"AU",
    iso3:"AUS",
    number:"036",
    currency_code:"AUD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Azerbaijan New Manat",
    coin:"Manat",
    country_handle:"Azerbaijan New",
    country_name:"Azerbaijan",
    iso2:"AZ",
    iso3:"AZE",
    number:"031",
    currency_code:"AZN",
    graphic:"",
    fonta:"???",
    font:"&#1084;&#1072;&#1085;",
    ariala:"???",
    arial:"&#1084;&#1072;&#1085;",
    decimal:"1084, 1072, 1085",
    hex:"43c, 430, 43d",
    comment:""
},{
    country:"Bahamas Dollar",
    coin:"Dollar",
    country_handle:"Bahamas",
    country_name:"Bahamas",
    iso2:"BS",
    iso3:"BHS",
    number:"044",
    currency_code:"BSD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Barbados Dollar",
    coin:"Dollar",
    country_handle:"Barbados",
    country_name:"Barbados",
    iso2:"BB",
    iso3:"BRB",
    number:"052",
    currency_code:"BBD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Belarus Ruble",
    coin:"Ruble",
    country_handle:"Belarus",
    country_name:"Belarus",
    iso2:"BY",
    iso3:"BLR",
    number:"112",
    currency_code:"BYR",
    graphic:"",
    fonta:"p.",
    font:"&#112;&#46;",
    ariala:"p.",
    arial:"&#112;&#46;",
    decimal:"112, 46",
    hex:"70, 2e",
    comment:""
},{
    country:"Belize Dollar",
    coin:"Dollar",
    country_handle:"Belize",
    country_name:"Belize",
    iso2:"BZ",
    iso3:"BLZ",
    number:"084",
    currency_code:"BZD",
    graphic:"",
    fonta:"BZ$",
    font:"&#66;&#90;&#36;",
    ariala:"BZ$",
    arial:"&#66;&#90;&#36;",
    decimal:"66, 90, 36",
    hex:"42, 5a, 24",
    comment:""
},{
    country:"Bermuda Dollar",
    coin:"Dollar",
    country_handle:"Bermuda",
    country_name:"Bermuda",
    iso2:"BM",
    iso3:"BMU",
    number:"060",
    currency_code:"BMD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Bolivia Bolíviano",
    coin:"Bolíviano",
    country_handle:"Bolivia",
    country_name:"Bolivia",
    iso2:"BO",
    iso3:"BOL",
    number:"068",
    currency_code:"BOB",
    graphic:"",
    fonta:"$b",
    font:"&#36;&#98;",
    ariala:"$b",
    arial:"&#36;&#98;",
    decimal:"36, 98",
    hex:"24, 62",
    comment:""
},{
    country:"Bosnia and Herzegovina Convertible Marka",
    coin:"Marka",
    country_handle:"Bosnia and Herzegovina Convertible",
    country_name:"Bosnia and Herzegovina",
    iso2:"BA",
    iso3:"BIH",
    number:"070",
    currency_code:"BAM",
    graphic:"",
    fonta:"KM",
    font:"&#75;&#77;",
    ariala:"KM",
    arial:"&#75;&#77;",
    decimal:"75, 77",
    hex:"4b, 4d",
    comment:""
},{
    country:"Botswana Pula",
    coin:"Pula",
    country_handle:"Botswana",
    country_name:"Botswana",
    iso2:"BW",
    iso3:"BWA",
    number:"072",
    currency_code:"BWP",
    graphic:"",
    fonta:"P",
    font:"&#80;",
    ariala:"P",
    arial:"&#80;",
    decimal:"80",
    hex:"50",
    comment:""
},{
    country:"Bulgaria Lev",
    coin:"Lev",
    country_handle:"Bulgaria",
    country_name:"Bulgaria",
    iso2:"BG",
    iso3:"BGR",
    number:"100",
    currency_code:"BGN",
    graphic:"",
    fonta:"??",
    font:"&#1083;&#1074;",
    ariala:"??",
    arial:"&#1083;&#1074;",
    decimal:"1083, 1074",
    hex:"43b, 432",
    comment:""
},{
    country:"Brazil Real",
    coin:"Real",
    country_handle:"Brazil",
    country_name:"Brazil",
    iso2:"BR",
    iso3:"BRA",
    number:"076",
    currency_code:"BRL",
    graphic:"",
    fonta:"R$",
    font:"&#82;&#36;",
    ariala:"R$",
    arial:"&#82;&#36;",
    decimal:"82, 36",
    hex:"52, 24",
    comment:"info"
},{
    country:"Brunei Darussalam Dollar",
    coin:"Dollar",
    country_handle:"Brunei Darussalam",
    country_name:"Brunei Darussalam",
    iso2:"BN",
    iso3:"BRN",
    number:"096",
    currency_code:"BND",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Cambodia Riel",
    coin:"Riel",
    country_handle:"Cambodia",
    country_name:"Cambodia",
    iso2:"KH",
    iso3:"KHM",
    number:"116",
    currency_code:"KHR",
    graphic:"",
    fonta:"?",
    font:"&#6107;",
    ariala:"?",
    arial:"&#6107;",
    decimal:"6107",
    hex:"17db",
    comment:""
},{
    country:"Canada Dollar",
    coin:"Dollar",
    country_handle:"Canada",
    country_name:"Canada",
    iso2:"CA",
    iso3:"CAN",
    number:"124",
    currency_code:"CAD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Cayman Islands Dollar",
    coin:"Dollar",
    country_handle:"Cayman Islands",
    country_name:"Cayman Islands",
    iso2:"KY",
    iso3:"CYM",
    number:"136",
    currency_code:"KYD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Chile Peso",
    coin:"Peso",
    country_handle:"Chile",
    country_name:"Chile",
    iso2:"CL",
    iso3:"CHL",
    number:"152",
    currency_code:"CLP",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:"info"
},{
    country:"China Yuan Renminbi",
    coin:"Yuan Renminbi",
    country_handle:"China",
    country_name:"China",
    iso2:"CN",
    iso3:"CHN",
    number:"156",
    currency_code:"CNY",
    graphic:"",
    fonta:"¥",
    font:"&#165;",
    ariala:"¥",
    arial:"&#165;",
    decimal:"165",
    hex:"a5",
    comment:"info"
},{
    country:"Colombia Peso",
    coin:"Peso",
    country_handle:"Colombia",
    country_name:"Colombia",
    iso2:"CO",
    iso3:"COL",
    number:"170",
    currency_code:"COP",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Costa Rica Colon",
    coin:"Colon",
    country_handle:"Costa Rica",
    country_name:"Costa Rica",
    iso2:"CR",
    iso3:"CRI",
    number:"188",
    currency_code:"CRC",
    graphic:"",
    fonta:"¢",
    font:"&#8353;",
    ariala:"¢",
    arial:"&#8353;",
    decimal:"8353",
    hex:"20a1",
    comment:""
},{
    country:"Croatia Kuna",
    coin:"Kuna",
    country_handle:"Croatia",
    country_name:"Croatia",
    iso2:"HR",
    iso3:"HRV",
    number:"191",
    currency_code:"HRK",
    graphic:"",
    fonta:"kn",
    font:"&#107;&#110;",
    ariala:"kn",
    arial:"&#107;&#110;",
    decimal:"107, 110",
    hex:"6b, 6e",
    comment:""
},{
    country:"Cuba Peso",
    coin:"Peso",
    country_handle:"Cuba",
    country_name:"Cuba",
    iso2:"CU",
    iso3:"CUB",
    number:"192",
    currency_code:"CUP",
    graphic:"",
    fonta:"?",
    font:"&#8369;",
    ariala:"?",
    arial:"&#8369;",
    decimal:"8369",
    hex:"20b1",
    comment:""
},{
    country:"Czech Republic Koruna",
    coin:"Koruna",
    country_handle:"Czech Republic",
    country_name:"Czech Republic",
    iso2:"CZ",
    iso3:"CZE",
    number:"203",
    currency_code:"CZK",
    graphic:"",
    fonta:"Kc",
    font:"&#75;&#269;",
    ariala:"Kc",
    arial:"&#75;&#269;",
    decimal:"75, 269",
    hex:"4b, 10d",
    comment:""
},{
    country:"Denmark Krone",
    coin:"Krone",
    country_handle:"Denmark",
    country_name:"Denmark",
    iso2:"DK",
    iso3:"DNK",
    number:"208",
    currency_code:"DKK",
    graphic:"",
    fonta:"kr",
    font:"&#107;&#114;",
    ariala:"kr",
    arial:"&#107;&#114;",
    decimal:"107, 114",
    hex:"6b, 72",
    comment:"info"
},{
    country:"Dominican Republic Peso",
    coin:"Peso",
    country_handle:"Dominican Republic",
    country_name:"Dominican Republic",
    iso2:"DO",
    iso3:"DOM",
    number:"214",
    currency_code:"DOP",
    graphic:"",
    fonta:"RD$",
    font:"&#82;&#68;&#36;",
    ariala:"RD$",
    arial:"&#82;&#68;&#36;",
    decimal:"82, 68, 36",
    hex:"52, 44, 24",
    comment:""
},{
    country:"East Caribbean Dollar",
    coin:"Dollar",
    country_handle:"East Caribbean",
    currency_code:"XCD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Egypt Pound",
    coin:"Pound",
    country_handle:"Egypt",
    country_name:"Egypt",
    iso2:"EG",
    iso3:"EGY",
    number:"818",
    currency_code:"EGP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"El Salvador Colon",
    coin:"Colon",
    country_handle:"El Salvador",
    country_name:"El Salvador",
    iso2:"SV",
    iso3:"SLV",
    number:"222",
    currency_code:"SVC",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Euro Member Countries",
    coin:"Countries",
    country_handle:"Euro Member",
    country_name:"Euro Member Countries",
    iso2:"EU",
    iso3:"EUR",
    number:"0",
    currency_code:"EUR",
    graphic:"",
    fonta:"€",
    font:"&#8364;",
    ariala:"€",
    arial:"&#8364;",
    decimal:"8364",
    hex:"20ac",
    comment:""
},{
    country:"Falkland Islands (Malvinas) Pound",
    coin:"Pound",
    country_handle:"Falkland Islands (Malvinas)",
    country_name:"Falkland Islands (Malvinas)",
    iso2:"FK",
    iso3:"FLK",
    number:"238",
    currency_code:"FKP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Fiji Dollar",
    coin:"Dollar",
    country_handle:"Fiji",
    country_name:"Fiji",
    iso2:"FJ",
    iso3:"FJI",
    number:"242",
    currency_code:"FJD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Ghana Cedi",
    coin:"Cedi",
    country_handle:"Ghana",
    country_name:"Ghana",
    iso2:"GH",
    iso3:"GHA",
    number:"288",
    currency_code:"GHS",
    graphic:"",
    fonta:"¢",
    font:"&#162;",
    ariala:"¢",
    arial:"&#162;",
    decimal:"162",
    hex:"a2",
    comment:""
},{
    country:"Gibraltar Pound",
    coin:"Pound",
    country_handle:"Gibraltar",
    country_name:"Gibraltar",
    iso2:"GI",
    iso3:"GIB",
    number:"292",
    currency_code:"GIP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Guatemala Quetzal",
    coin:"Quetzal",
    country_handle:"Guatemala",
    country_name:"Guatemala",
    iso2:"GT",
    iso3:"GTM",
    number:"320",
    currency_code:"GTQ",
    graphic:"",
    fonta:"Q",
    font:"&#81;",
    ariala:"Q",
    arial:"&#81;",
    decimal:"81",
    hex:"51",
    comment:""
},{
    country:"Guernsey Pound",
    coin:"Pound",
    country_handle:"Guernsey",
    country_name:"Guernsey",
    iso2:"GG",
    iso3:"GGY",
    number:"831",
    currency_code:"GGP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Guyana Dollar",
    coin:"Dollar",
    country_handle:"Guyana",
    country_name:"Guyana",
    iso2:"GY",
    iso3:"GUY",
    number:"328",
    currency_code:"GYD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Honduras Lempira",
    coin:"Lempira",
    country_handle:"Honduras",
    country_name:"Honduras",
    iso2:"HN",
    iso3:"HND",
    number:"340",
    currency_code:"HNL",
    graphic:"",
    fonta:"L",
    font:"&#76;",
    ariala:"L",
    arial:"&#76;",
    decimal:"76",
    hex:"4c",
    comment:""
},{
    country:"Hong Kong Dollar",
    coin:"Dollar",
    country_handle:"Hong Kong",
    country_name:"Hong Kong, Special Administrative Region of China",
    iso2:"HK",
    iso3:"HKG",
    number:"344",
    currency_code:"HKD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:"info"
},{
    country:"Hungary Forint",
    coin:"Forint",
    country_handle:"Hungary",
    country_name:"Hungary",
    iso2:"HU",
    iso3:"HUN",
    number:"348",
    currency_code:"HUF",
    graphic:"",
    fonta:"Ft",
    font:"&#70;&#116;",
    ariala:"Ft",
    arial:"&#70;&#116;",
    decimal:"70, 116",
    hex:"46, 74",
    comment:""
},{
    country:"Iceland Krona",
    coin:"Krona",
    country_handle:"Iceland",
    country_name:"Iceland",
    iso2:"IS",
    iso3:"ISL",
    number:"352",
    currency_code:"ISK",
    graphic:"",
    fonta:"kr",
    font:"&#107;&#114;",
    ariala:"kr",
    arial:"&#107;&#114;",
    decimal:"107, 114",
    hex:"6b, 72",
    comment:""
},{
    country:"India Rupee",
    coin:"Rupee",
    country_handle:"India",
    country_name:"India",
    iso2:"IN",
    iso3:"IND",
    number:"356",
    currency_code:"INR",
    graphic:"",
    fonta:"",
    font:"",
    ariala:"",
    arial:"",
    decimal:"",
    hex:"",
    comment:"info"
},{
    country:"Indonesia Rupiah",
    coin:"Rupiah",
    country_handle:"Indonesia",
    country_name:"Indonesia",
    iso2:"ID",
    iso3:"IDN",
    number:"360",
    currency_code:"IDR",
    graphic:"",
    fonta:"Rp",
    font:"&#82;&#112;",
    ariala:"Rp",
    arial:"&#82;&#112;",
    decimal:"82, 112",
    hex:"52, 70",
    comment:""
},{
    country:"Iran Rial",
    coin:"Rial",
    country_handle:"Iran",
    country_name:"Iran, Islamic Republic of",
    iso2:"IR",
    iso3:"IRN",
    number:"364",
    currency_code:"IRR",
    graphic:"",
    fonta:"?",
    font:"&#65020;",
    ariala:"?",
    arial:"&#65020;",
    decimal:"65020",
    hex:"fdfc",
    comment:""
},{
    country:"Isle of Man Pound",
    coin:"Pound",
    country_handle:"Isle of Man",
    country_name:"Isle of Man",
    iso2:"IM",
    iso3:"IMN",
    number:"833",
    currency_code:"IMP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Israel Shekel",
    coin:"Shekel",
    country_handle:"Israel",
    country_name:"Israel",
    iso2:"IL",
    iso3:"ISR",
    number:"376",
    currency_code:"ILS",
    graphic:"",
    fonta:"?",
    font:"&#8362;",
    ariala:"?",
    arial:"&#8362;",
    decimal:"8362",
    hex:"20aa",
    comment:""
},{
    country:"Jamaica Dollar",
    coin:"Dollar",
    country_handle:"Jamaica",
    country_name:"Jamaica",
    iso2:"JM",
    iso3:"JAM",
    number:"388",
    currency_code:"JMD",
    graphic:"",
    fonta:"J$",
    font:"&#74;&#36;",
    ariala:"J$",
    arial:"&#74;&#36;",
    decimal:"74, 36",
    hex:"4a, 24",
    comment:""
},{
    country:"Japan Yen",
    coin:"Yen",
    country_handle:"Japan",
    country_name:"Japan",
    iso2:"JP",
    iso3:"JPN",
    number:"392",
    currency_code:"JPY",
    graphic:"",
    fonta:"¥",
    font:"&#165;",
    ariala:"¥",
    arial:"&#165;",
    decimal:"165",
    hex:"a5",
    comment:"info"
},{
    country:"Jersey Pound",
    coin:"Pound",
    country_handle:"Jersey",
    country_name:"Jersey",
    iso2:"JE",
    iso3:"JEY",
    number:"832",
    currency_code:"JEP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Kazakhstan Tenge",
    coin:"Tenge",
    country_handle:"Kazakhstan",
    country_name:"Kazakhstan",
    iso2:"KZ",
    iso3:"KAZ",
    number:"398",
    currency_code:"KZT",
    graphic:"",
    fonta:"??",
    font:"&#1083;&#1074;",
    ariala:"??",
    arial:"&#1083;&#1074;",
    decimal:"1083, 1074",
    hex:"43b, 432",
    comment:""
},{
    country:"Korea (North) Won",
    coin:"Won",
    country_handle:"Korea (North)",
    country_name:"Korea, Democratic People's Republic of",
    iso2:"KP",
    iso3:"PRK",
    number:"408",
    currency_code:"KPW",
    graphic:"",
    fonta:"?",
    font:"&#8361;",
    ariala:"?",
    arial:"&#8361;",
    decimal:"8361",
    hex:"20a9",
    comment:""
},{
    country:"Korea (South) Won",
    coin:"Won",
    country_handle:"Korea (South)",
    country_name:"Korea, Republic of",
    iso2:"KR",
    iso3:"KOR",
    number:"410",
    currency_code:"KRW",
    graphic:"",
    fonta:"?",
    font:"&#8361;",
    ariala:"?",
    arial:"&#8361;",
    decimal:"8361",
    hex:"20a9",
    comment:""
},{
    country:"Kyrgyzstan Som",
    coin:"Som",
    country_handle:"Kyrgyzstan",
    country_name:"Kyrgyzstan",
    iso2:"KG",
    iso3:"KGZ",
    number:"417",
    currency_code:"KGS",
    graphic:"",
    fonta:"??",
    font:"&#1083;&#1074;",
    ariala:"??",
    arial:"&#1083;&#1074;",
    decimal:"1083, 1074",
    hex:"43b, 432",
    comment:""
},{
    country:"Laos Kip",
    coin:"Kip",
    country_handle:"Laos",
    country_name:"Lao PDR",
    iso2:"LA",
    iso3:"LAO",
    number:"418",
    currency_code:"LAK",
    graphic:"",
    fonta:"?",
    font:"&#8365;",
    ariala:"?",
    arial:"&#8365;",
    decimal:"8365",
    hex:"20ad",
    comment:""
},{
    country:"Lebanon Pound",
    coin:"Pound",
    country_handle:"Lebanon",
    country_name:"Lebanon",
    iso2:"LB",
    iso3:"LBN",
    number:"422",
    currency_code:"LBP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Liberia Dollar",
    coin:"Dollar",
    country_handle:"Liberia",
    country_name:"Liberia",
    iso2:"LR",
    iso3:"LBR",
    number:"430",
    currency_code:"LRD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Macedonia Denar",
    coin:"Denar",
    country_handle:"Macedonia",
    country_name:"Macedonia, Republic of",
    iso2:"MK",
    iso3:"MKD",
    number:"807",
    currency_code:"MKD",
    graphic:"",
    fonta:"???",
    font:"&#1076;&#1077;&#1085;",
    ariala:"???",
    arial:"&#1076;&#1077;&#1085;",
    decimal:"1076, 1077, 1085",
    hex:"434, 435, 43d",
    comment:""
},{
    country:"Malaysia Ringgit",
    coin:"Ringgit",
    country_handle:"Malaysia",
    country_name:"Malaysia",
    iso2:"MY",
    iso3:"MYS",
    number:"458",
    currency_code:"MYR",
    graphic:"",
    fonta:"RM",
    font:"&#82;&#77;",
    ariala:"RM",
    arial:"&#82;&#77;",
    decimal:"82, 77",
    hex:"52, 4d",
    comment:""
},{
    country:"Mauritius Rupee",
    coin:"Rupee",
    country_handle:"Mauritius",
    country_name:"Mauritius",
    iso2:"MU",
    iso3:"MUS",
    number:"480",
    currency_code:"MUR",
    graphic:"",
    fonta:"?",
    font:"&#8360;",
    ariala:"?",
    arial:"&#8360;",
    decimal:"8360",
    hex:"20a8",
    comment:""
},{
    country:"Mexico Peso",
    coin:"Peso",
    country_handle:"Mexico",
    country_name:"Mexico",
    iso2:"MX",
    iso3:"MEX",
    number:"484",
    currency_code:"MXN",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:"info"
},{
    country:"Mongolia Tughrik",
    coin:"Tughrik",
    country_handle:"Mongolia",
    country_name:"Mongolia",
    iso2:"MN",
    iso3:"MNG",
    number:"496",
    currency_code:"MNT",
    graphic:"",
    fonta:"?",
    font:"&#8366;",
    ariala:"?",
    arial:"&#8366;",
    decimal:"8366",
    hex:"20ae",
    comment:""
},{
    country:"Mozambique Metical",
    coin:"Metical",
    country_handle:"Mozambique",
    country_name:"Mozambique",
    iso2:"MZ",
    iso3:"MOZ",
    number:"508",
    currency_code:"MZN",
    graphic:"",
    fonta:"MT",
    font:"&#77;&#84;",
    ariala:"MT",
    arial:"&#77;&#84;",
    decimal:"77, 84",
    hex:"4d, 54",
    comment:""
},{
    country:"Namibia Dollar",
    coin:"Dollar",
    country_handle:"Namibia",
    country_name:"Namibia",
    iso2:"NA",
    iso3:"NAM",
    number:"516",
    currency_code:"NAD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Nepal Rupee",
    coin:"Rupee",
    country_handle:"Nepal",
    country_name:"Nepal",
    iso2:"NP",
    iso3:"NPL",
    number:"524",
    currency_code:"NPR",
    graphic:"",
    fonta:"?",
    font:"&#8360;",
    ariala:"?",
    arial:"&#8360;",
    decimal:"8360",
    hex:"20a8",
    comment:""
},{
    country:"Netherlands Antilles Guilder",
    coin:"Guilder",
    country_handle:"Netherlands Antilles",
    country_name:"Netherlands Antilles",
    iso2:"AN",
    iso3:"ANT",
    number:"530",
    currency_code:"ANG",
    graphic:"",
    fonta:"ƒ",
    font:"&#402;",
    ariala:"ƒ",
    arial:"&#402;",
    decimal:"402",
    hex:"192",
    comment:""
},{
    country:"New Zealand Dollar",
    coin:"Dollar",
    country_handle:"New Zealand",
    country_name:"New Zealand",
    iso2:"NZ",
    iso3:"NZL",
    number:"554",
    currency_code:"NZD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Nicaragua Cordoba",
    coin:"Cordoba",
    country_handle:"Nicaragua",
    country_name:"Nicaragua",
    iso2:"NI",
    iso3:"NIC",
    number:"558",
    currency_code:"NIO",
    graphic:"",
    fonta:"C$",
    font:"&#67;&#36;",
    ariala:"C$",
    arial:"&#67;&#36;",
    decimal:"67, 36",
    hex:"43, 24",
    comment:""
},{
    country:"Nigeria Naira",
    coin:"Naira",
    country_handle:"Nigeria",
    country_name:"Nigeria",
    iso2:"NG",
    iso3:"NGA",
    number:"566",
    currency_code:"NGN",
    graphic:"",
    fonta:"?",
    font:"&#8358;",
    ariala:"?",
    arial:"&#8358;",
    decimal:"8358",
    hex:"20a6",
    comment:""
},{
    country:"Korea (North) Won",
    coin:"Won",
    country_handle:"Korea (North)",
    country_name:"Korea, Democratic People's Republic of",
    iso2:"KP",
    iso3:"PRK",
    number:"408",
    currency_code:"KPW",
    graphic:"",
    fonta:"?",
    font:"&#8361;",
    ariala:"?",
    arial:"&#8361;",
    decimal:"8361",
    hex:"20a9",
    comment:""
},{
    country:"Norway Krone",
    coin:"Krone",
    country_handle:"Norway",
    country_name:"Norway",
    iso2:"NO",
    iso3:"NOR",
    number:"578",
    currency_code:"NOK",
    graphic:"",
    fonta:"kr",
    font:"&#107;&#114;",
    ariala:"kr",
    arial:"&#107;&#114;",
    decimal:"107, 114",
    hex:"6b, 72",
    comment:""
},{
    country:"Oman Rial",
    coin:"Rial",
    country_handle:"Oman",
    country_name:"Oman",
    iso2:"OM",
    iso3:"OMN",
    number:"512",
    currency_code:"OMR",
    graphic:"",
    fonta:"?",
    font:"&#65020;",
    ariala:"?",
    arial:"&#65020;",
    decimal:"65020",
    hex:"fdfc",
    comment:""
},{
    country:"Pakistan Rupee",
    coin:"Rupee",
    country_handle:"Pakistan",
    country_name:"Pakistan",
    iso2:"PK",
    iso3:"PAK",
    number:"586",
    currency_code:"PKR",
    graphic:"",
    fonta:"?",
    font:"&#8360;",
    ariala:"?",
    arial:"&#8360;",
    decimal:"8360",
    hex:"20a8",
    comment:""
},{
    country:"Panama Balboa",
    coin:"Balboa",
    country_handle:"Panama",
    country_name:"Panama",
    iso2:"PA",
    iso3:"PAN",
    number:"591",
    currency_code:"PAB",
    graphic:"",
    fonta:"B/.",
    font:"&#66;&#47;&#46;",
    ariala:"B/.",
    arial:"&#66;&#47;&#46;",
    decimal:"66, 47, 46",
    hex:"42, 2f, 2e",
    comment:""
},{
    country:"Paraguay Guarani",
    coin:"Guarani",
    country_handle:"Paraguay",
    country_name:"Paraguay",
    iso2:"PY",
    iso3:"PRY",
    number:"600",
    currency_code:"PYG",
    graphic:"",
    fonta:"Gs",
    font:"&#71;&#115;",
    ariala:"Gs",
    arial:"&#71;&#115;",
    decimal:"71, 115",
    hex:"47, 73",
    comment:""
},{
    country:"Peru Sol",
    coin:"Sol",
    country_handle:"Peru",
    country_name:"Peru",
    iso2:"PE",
    iso3:"PER",
    number:"604",
    currency_code:"PEN",
    graphic:"",
    fonta:"S/.",
    font:"&#83;&#47;&#46;",
    ariala:"S/.",
    arial:"&#83;&#47;&#46;",
    decimal:"83, 47, 46",
    hex:"53, 2f, 2e",
    comment:"info"
},{
    country:"Philippines Peso",
    coin:"PPeso",
    country_handle:"Philippines",
    country_name:"Philippines",
    iso2:"PH",
    iso3:"PHL",
    number:"608",
    currency_code:"PHP",
    graphic:"",
    fonta:"?",
    font:"&#8369;",
    ariala:"?",
    arial:"&#8369;",
    decimal:"8369",
    hex:"20b1",
    comment:""
},{
    country:"Poland Zloty",
    coin:"Zloty",
    country_handle:"Poland",
    country_name:"Poland",
    iso2:"PL",
    iso3:"POL",
    number:"616",
    currency_code:"PLN",
    graphic:"",
    fonta:"zl",
    font:"&#122;&#322;",
    ariala:"zl",
    arial:"&#122;&#322;",
    decimal:"122, 322",
    hex:"7a, 142",
    comment:""
},{
    country:"Qatar Riyal",
    coin:"Riyal",
    country_handle:"Qatar",
    country_name:"Qatar",
    iso2:"QA",
    iso3:"QAT",
    number:"634",
    currency_code:"QAR",
    graphic:"",
    fonta:"?",
    font:"&#65020;",
    ariala:"?",
    arial:"&#65020;",
    decimal:"65020",
    hex:"fdfc",
    comment:""
},{
    country:"Romania New Leu",
    coin:"Leu",
    country_handle:"Romania New",
    country_name:"Romania",
    iso2:"RO",
    iso3:"ROU",
    number:"642",
    currency_code:"RON",
    graphic:"",
    fonta:"lei",
    font:"&#108;&#101;&#105;",
    ariala:"lei",
    arial:"&#108;&#101;&#105;",
    decimal:"108, 101, 105",
    hex:"6c, 65, 69",
    comment:""
},{
    country:"Russia Ruble",
    coin:"Ruble",
    country_handle:"Russia",
    country_name:"Russian Federation",
    iso2:"RU",
    iso3:"RUS",
    number:"643",
    currency_code:"RUB",
    graphic:"",
    fonta:"???",
    font:"&#1088;&#1091;&#1073;",
    ariala:"???",
    arial:"&#1088;&#1091;&#1073;",
    decimal:"1088, 1091, 1073",
    hex:"440, 443, 431",
    comment:"info"
},{
    country:"Saint Helena Pound",
    coin:"Pound",
    country_handle:"Saint Helena",
    country_name:"Saint Helena",
    iso2:"SH",
    iso3:"SHN",
    number:"654",
    currency_code:"SHP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Saudi Arabia Riyal",
    coin:"Riyal",
    country_handle:"Saudi Arabia",
    country_name:"Saudi Arabia",
    iso2:"SA",
    iso3:"SAU",
    number:"682",
    currency_code:"SAR",
    graphic:"",
    fonta:"?",
    font:"&#65020;",
    ariala:"?",
    arial:"&#65020;",
    decimal:"65020",
    hex:"fdfc",
    comment:""
},{
    country:"Serbia Dinar",
    coin:"Dinar",
    country_handle:"Serbia",
    country_name:"Serbia",
    iso2:"RS",
    iso3:"SRB",
    number:"688",
    currency_code:"RSD",
    graphic:"",
    fonta:"???.",
    font:"&#1044;&#1080;&#1085;&#46;",
    ariala:"???.",
    arial:"&#1044;&#1080;&#1085;&#46;",
    decimal:"1044, 1080, 1085, 46",
    hex:"414, 438, 43d, 2e",
    comment:""
},{
    country:"Seychelles Rupee",
    coin:"Rupee",
    country_handle:"Seychelles",
    country_name:"Seychelles",
    iso2:"SC",
    iso3:"SYC",
    number:"690",
    currency_code:"SCR",
    graphic:"",
    fonta:"?",
    font:"&#8360;",
    ariala:"?",
    arial:"&#8360;",
    decimal:"8360",
    hex:"20a8",
    comment:""
},{
    country:"Singapore Dollar",
    coin:"Dollar",
    country_handle:"Singapore",
    country_name:"Singapore",
    iso2:"SG",
    iso3:"SGP",
    number:"702",
    currency_code:"SGD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Solomon Islands Dollar",
    coin:"Dollar",
    country_handle:"Solomon Islands",
    country_name:"Solomon Islands",
    iso2:"SB",
    iso3:"SLB",
    number:"090",
    currency_code:"SBD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Somalia Shilling",
    coin:"Shilling",
    country_handle:"Somalia",
    country_name:"Somalia",
    iso2:"SO",
    iso3:"SOM",
    number:"706",
    currency_code:"SOS",
    graphic:"",
    fonta:"S",
    font:"&#83;",
    ariala:"S",
    arial:"&#83;",
    decimal:"83",
    hex:"53",
    comment:""
},{
    country:"South Africa Rand",
    coin:"Rand",
    country_handle:"South Africa",
    country_name:"South Africa",
    iso2:"ZA",
    iso3:"ZAF",
    number:"710",
    currency_code:"ZAR",
    graphic:"",
    fonta:"R",
    font:"&#82;",
    ariala:"R",
    arial:"&#82;",
    decimal:"82",
    hex:"52",
    comment:""
},{
    country:"Korea (South) Won",
    coin:"Won",
    country_handle:"Korea (South)",
    country_name:"Korea, Republic of",
    iso2:"KR",
    iso3:"KOR",
    number:"410",
    currency_code:"KRW",
    graphic:"",
    fonta:"?",
    font:"&#8361;",
    ariala:"?",
    arial:"&#8361;",
    decimal:"8361",
    hex:"20a9",
    comment:""
},{
    country:"Sri Lanka Rupee",
    coin:"Rupee",
    country_handle:"Sri Lanka",
    country_name:"Sri Lanka",
    iso2:"LK",
    iso3:"LKA",
    number:"144",
    currency_code:"LKR",
    graphic:"",
    fonta:"?",
    font:"&#8360;",
    ariala:"?",
    arial:"&#8360;",
    decimal:"8360",
    hex:"20a8",
    comment:""
},{
    country:"Sweden Krona",
    coin:"Krona",
    country_handle:"Sweden",
    country_name:"Sweden",
    iso2:"SE",
    iso3:"SWE",
    number:"752",
    currency_code:"SEK",
    graphic:"",
    fonta:"kr",
    font:"&#107;&#114;",
    ariala:"kr",
    arial:"&#107;&#114;",
    decimal:"107, 114",
    hex:"6b, 72",
    comment:"info"
},{
    country:"Switzerland Franc",
    coin:"Franc",
    country_handle:"Switzerland",
    country_name:"Switzerland",
    iso2:"CH",
    iso3:"CHE",
    number:"756",
    currency_code:"CHF",
    graphic:"",
    fonta:"CHF",
    font:"&#67;&#72;&#70;",
    ariala:"CHF",
    arial:"&#67;&#72;&#70;",
    decimal:"67, 72, 70",
    hex:"43, 48, 46",
    comment:""
},{
    country:"Suriname Dollar",
    coin:"Dollar",
    country_handle:"Suriname",
    country_name:"Suriname *",
    iso2:"SR",
    iso3:"SUR",
    number:"740",
    currency_code:"SRD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Syria Pound",
    coin:"Pound",
    country_handle:"Syria",
    country_name:"Syrian Arab Republic (Syria)",
    iso2:"SY",
    iso3:"SYR",
    number:"760",
    currency_code:"SYP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"Taiwan New Dollar",
    coin:"Dollar",
    country_handle:"Taiwan New",
    country_name:"Taiwan, Republic of China",
    iso2:"TW",
    iso3:"TWN",
    number:"158",
    currency_code:"TWD",
    graphic:"",
    fonta:"NT$",
    font:"&#78;&#84;&#36;",
    ariala:"NT$",
    arial:"&#78;&#84;&#36;",
    decimal:"78, 84, 36",
    hex:"4e, 54, 24",
    comment:"info"
},{
    country:"Thailand Baht",
    coin:"Baht",
    country_handle:"Thailand",
    country_name:"Thailand",
    iso2:"TH",
    iso3:"THA",
    number:"764",
    currency_code:"THB",
    graphic:"",
    fonta:"?",
    font:"&#3647;",
    ariala:"?",
    arial:"&#3647;",
    decimal:"3647",
    hex:"e3f",
    comment:""
},{
    country:"Trinidad and Tobago Dollar",
    coin:"Dollar",
    country_handle:"Trinidad and Tobago",
    country_name:"Trinidad and Tobago",
    iso2:"TT",
    iso3:"TTO",
    number:"780",
    currency_code:"TTD",
    graphic:"",
    fonta:"TT$",
    font:"&#84;&#84;&#36;",
    ariala:"TT$",
    arial:"&#84;&#84;&#36;",
    decimal:"84, 84, 36",
    hex:"54, 54, 24",
    comment:""
},{
    country:"Turkey Lira",
    coin:"Lira",
    country_handle:"Turkey",
    country_name:"Turkey",
    iso2:"TR",
    iso3:"TUR",
    number:"792",
    currency_code:"TRY",
    graphic:"",
    fonta:"",
    font:"",
    ariala:"",
    arial:"",
    decimal:"",
    hex:"",
    comment:"info"
},{
    country:"Tuvalu Dollar",
    coin:"Dollar",
    country_handle:"Tuvalu",
    country_name:"Tuvalu",
    iso2:"TV",
    iso3:"TUV",
    number:"798",
    currency_code:"TVD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Ukraine Hryvnia",
    coin:"Hryvnia",
    country_handle:"Ukraine",
    country_name:"Ukraine",
    iso2:"UA",
    iso3:"UKR",
    number:"804",
    currency_code:"UAH",
    graphic:"",
    fonta:"?",
    font:"&#8372;",
    ariala:"?",
    arial:"&#8372;",
    decimal:"8372",
    hex:"20b4",
    comment:""
},{
    country:"United Kingdom Pound",
    coin:"Pound",
    country_handle:"United Kingdom",
    country_name:"United Kingdom",
    iso2:"GB",
    iso3:"GBR",
    number:"826",
    currency_code:"GBP",
    graphic:"",
    fonta:"£",
    font:"&#163;",
    ariala:"£",
    arial:"&#163;",
    decimal:"163",
    hex:"a3",
    comment:""
},{
    country:"United States Dollar",
    coin:"Dollar",
    country_handle:"United States",
    country_name:"United States of America",
    iso2:"US",
    iso3:"USA",
    number:"840",
    currency_code:"USD",
    graphic:"",
    fonta:"$",
    font:"&#36;",
    ariala:"$",
    arial:"&#36;",
    decimal:"36",
    hex:"24",
    comment:""
},{
    country:"Uruguay Peso",
    coin:"Peso",
    country_handle:"Uruguay",
    country_name:"Uruguay",
    iso2:"UY",
    iso3:"URY",
    number:"858",
    currency_code:"UYU",
    graphic:"",
    fonta:"$U",
    font:"&#36;&#85;",
    ariala:"$U",
    arial:"&#36;&#85;",
    decimal:"36, 85",
    hex:"24, 55",
    comment:""
},{
    country:"Uzbekistan Som",
    coin:"Som",
    country_handle:"Uzbekistan",
    country_name:"Uzbekistan",
    iso2:"UZ",
    iso3:"UZB",
    number:"860",
    currency_code:"UZS",
    graphic:"",
    fonta:"??",
    font:"&#1083;&#1074;",
    ariala:"??",
    arial:"&#1083;&#1074;",
    decimal:"1083, 1074",
    hex:"43b, 432",
    comment:""
},{
    country:"Venezuela Bolivar",
    coin:"Bolivar",
    country_handle:"Venezuela",
    country_name:"Venezuela (Bolivarian Republic of)",
    iso2:"VE",
    iso3:"VEN",
    number:"862",
    currency_code:"VEF",
    graphic:"",
    fonta:"Bs",
    font:"&#66;&#115;",
    ariala:"Bs",
    arial:"&#66;&#115;",
    decimal:"66, 115",
    hex:"42, 73",
    comment:""
},{
    country:"Viet Nam Dong",
    coin:"Dong",
    country_handle:"Viet Nam",
    country_name:"Viet Nam",
    iso2:"VN",
    iso3:"VNM",
    number:"704",
    currency_code:"VND",
    graphic:"",
    fonta:"?",
    font:"&#8363;",
    ariala:"?",
    arial:"&#8363;",
    decimal:"8363",
    hex:"20ab",
    comment:""
},{
    country:"Yemen Rial",
    coin:"Rial",
    country_handle:"Yemen",
    country_name:"Yemen",
    iso2:"YE",
    iso3:"YEM",
    number:"887",
    currency_code:"YER",
    graphic:"",
    fonta:"?",
    font:"&#65020;",
    ariala:"?",
    arial:"&#65020;",
    decimal:"65020",
    hex:"fdfc",
    comment:""
},{
    country:"Zimbabwe Dollar",
    coin:"Dollar",
    country_handle:"Zimbabwe",
    country_name:"Zimbabwe",
    iso2:"ZW",
    iso3:"ZWE",
    number:"716",
    currency_code:"ZWD",
    graphic:"",
    fonta:"Z$",
    font:"&#90;&#36;",
    ariala:"Z$",
    arial:"&#90;&#36;",
    decimal:"90, 36",
    hex:"5a, 24",
    comment:""
}







